version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Caltec.StudentInfoProject.WebUi"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/Caltec.StudentInfoProject.Persistence"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/Caltec.StudentInfoProject.Business.Tests"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
# add comment to force trigger Dependabot
# Force run
